/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: packages/ui/src/theme/pam.theme.ts
 * Command: pnpm --filter @pam/ui theme  (astryx theme build src/theme/pam.theme.ts, from packages/ui)
 * CLI: @astryxdesign/cli@0.6.0
 * Core: @astryxdesign/core@0.6.0
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
