-- 0002 — Identity: regions, profiles, orgs, invites, caseload assignment.
--
-- PAM is closed (§4.1). There is no open signup path and no self-service role
-- change: `invites` is the only way in, and the invite carries the role.

create table public.regions (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,
  center_geo    extensions.geography(Point, 4326),
  admin_org_name text,
  created_at    timestamptz not null default now()
);

comment on table public.regions is
  'A supervising area. An admin sees only their own region (SOP §4 RLS rules).';

create table public.orgs (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  type       text,
  address    text,
  geo        extensions.geography(Point, 4326),
  phone      text,
  website    text,
  -- §6.4: a provider is only shown as a mentor with an org badge once verified.
  -- Admin-invited orgs are pre-verified (§4.1 step 3).
  verified   boolean not null default false,
  verified_by uuid,
  verified_at timestamptz,
  region_id  uuid references public.regions (id) on delete set null,
  created_at timestamptz not null default now()
);

create index orgs_region_idx on public.orgs (region_id);
create index orgs_geo_idx on public.orgs using gist (geo);

-- profiles.id IS auth.users.id. Auth is phone-only (Twilio Verify, §9), so
-- there is no email column here by design.
create table public.profiles (
  id                 uuid primary key references auth.users (id) on delete cascade,
  role               public.user_role not null,
  first_name         text,
  display_name       text,
  photo_url          text,
  -- E.164. Enforced rather than documented: a malformed number silently drops
  -- every reminder for that member.
  phone              text unique,
  preferred_language text not null default 'en',
  home_zip           text,
  bio                text,
  tags               text[] not null default '{}',
  is_mentor          boolean not null default false,
  -- §4 RLS: is_public = false hides this member from ALL search and discovery.
  is_public          boolean not null default false,
  org_id             uuid references public.orgs (id) on delete set null,
  region_id          uuid references public.regions (id) on delete set null,
  invited_by         uuid references public.profiles (id) on delete set null,
  access_status      public.access_status not null default 'active',
  last_active_at     timestamptz,
  onboarded_at       timestamptz,
  -- §10 step 9: the transparency screen cannot be skipped. Recording the ack
  -- lets us prove a member saw it, and re-show it if the contract ever changes.
  transparency_ack_at timestamptz,
  created_at         timestamptz not null default now(),

  constraint profiles_phone_e164 check (phone is null or phone ~ '^\+[1-9]\d{7,14}$'),
  constraint profiles_language_supported check (preferred_language in ('en', 'es')),
  -- A provider belongs to an org; an admin belongs to a region. Enforced so a
  -- half-built account cannot slip past the invite flow.
  constraint profiles_admin_has_region check (role <> 'admin' or region_id is not null)
);

create index profiles_role_idx on public.profiles (role);
create index profiles_region_idx on public.profiles (region_id);
create index profiles_org_idx on public.profiles (org_id);
create index profiles_mentor_discovery_idx on public.profiles (is_mentor, is_public)
  where is_mentor and is_public;

comment on column public.profiles.is_public is
  'False hides this person from every search and discovery surface (SOP §4).';

-- ---------------------------------------------------------------------------
-- Invites — the only door into PAM (§4.1).
-- ---------------------------------------------------------------------------

create table public.invites (
  id               uuid primary key default gen_random_uuid(),
  -- 8 human-readable characters, no ambiguous glyphs, so it can be read aloud
  -- over the phone. Generated by public.generate_invite_code().
  code             text not null unique,
  created_by       uuid not null references public.profiles (id) on delete cascade,
  role             public.user_role not null,
  region_id        uuid references public.regions (id) on delete set null,
  -- Optional prefill. When present, §10 step 4 requires the verified phone to
  -- match, so a code read aloud in a waiting room cannot be used by a bystander.
  phone            text,
  assigned_admin_id uuid references public.profiles (id) on delete set null,
  expires_at       timestamptz not null default (now() + interval '30 days'),
  redeemed_by      uuid references public.profiles (id) on delete set null,
  redeemed_at      timestamptz,
  status           public.invite_status not null default 'pending',
  created_at       timestamptz not null default now(),

  -- An invite creates a member or a provider. Admins are made by another admin
  -- from the Admin Panel or by the seed script, never by redeeming a code.
  constraint invites_role_not_admin check (role in ('member', 'provider')),
  constraint invites_phone_e164 check (phone is null or phone ~ '^\+[1-9]\d{7,14}$'),
  constraint invites_redeemed_consistently check (
    (status = 'redeemed') = (redeemed_by is not null and redeemed_at is not null)
  )
);

create index invites_code_idx on public.invites (code) where status = 'pending';
create index invites_created_by_idx on public.invites (created_by);
create index invites_region_idx on public.invites (region_id);

-- ---------------------------------------------------------------------------
-- Caseload.
-- ---------------------------------------------------------------------------

create table public.admin_assignments (
  id          uuid primary key default gen_random_uuid(),
  admin_id    uuid not null references public.profiles (id) on delete cascade,
  member_id   uuid not null references public.profiles (id) on delete cascade,
  assigned_at timestamptz not null default now(),
  ended_at    timestamptz,

  constraint admin_assignments_distinct check (admin_id <> member_id)
);

-- A member has at most one ACTIVE admin at a time; history is kept by ended_at.
create unique index admin_assignments_active_uniq
  on public.admin_assignments (member_id)
  where ended_at is null;

create index admin_assignments_admin_idx
  on public.admin_assignments (admin_id) where ended_at is null;

comment on table public.admin_assignments is
  'Caseload. An admin reaches a member through this table or a shared region_id.';
