/**
 * A contact sheet of every screen, for every kind of person, in both themes.
 *
 * The problem this solves: PAM has four roles and a Twilio account that will
 * only text one verified number, so "sign in as a program manager and look" is
 * not available — and will not be until the carrier registration clears. Even
 * then, walking six screens in four roles by hand is twenty minutes nobody
 * spends before shipping a copy change.
 *
 * So the screens are photographed against stubbed data: real pages, real
 * components, real CSS, fake answers from the network. Every run writes
 * docs/journeys/<role>/<screen>.png and an index.html that lays them out side
 * by side. Open that file in a browser and the whole product is in front of
 * you.
 *
 * What it is not: a test. Nothing here asserts anything — e2e/ does that. This
 * is for looking, which is the thing no assertion replaces (the unthemed-build
 * disaster in DECISIONS D-008 passed every check it had).
 *
 *   pnpm --filter @pam/web build && node scripts/journeys.mjs
 */
import { chromium } from '@playwright/test';
import { mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { spawn } from 'node:child_process';

/**
 * Written into the built site by default, so the sheet ships with the app and
 * is regenerated by every deploy — always the current screens, never a folder
 * somebody forgot to refresh. Override with JOURNEYS_OUT to put it elsewhere.
 */
const OUT =
  process.env.JOURNEYS_OUT ?? new URL('../apps/web/out/journeys/', import.meta.url).pathname;
const PORT = 3123;
const BASE = `http://127.0.0.1:${PORT}`;
const ADMIN_ID = 'de3b9c2e-ec2f-403b-93e5-86e6ee75349b';
const OTHER_ID = '7c1f8c1e-1c7e-4a5c-9d6e-0f3a2b4c5d6e';
const CONVO_ID = '2a9d5e1c-3b7f-4d8e-9a1b-6c5d4e3f2a1b';

const json = (body) => ({
  status: 200,
  contentType: 'application/json',
  body: JSON.stringify(body),
});

/**
 * Everyone PAM serves, what the database would say about them, and how to
 * describe them to somebody reviewing the sheet.
 */
const ROLES = {
  'signed-out': {
    profile: null,
    title: 'Not signed in',
    note: 'What anybody sees before they have an account — including a carrier reviewing the registration.',
  },
  member: {
    profile: { role: 'member', first_name: 'Marcus' },
    title: 'Member',
    note: 'Somebody using PAM to find help and keep track of what they planned.',
  },
  provider: {
    profile: { role: 'provider', first_name: 'Alice' },
    title: 'Program manager',
    note: 'Runs a programme. Lists services, hears when somebody is introduced to them.',
  },
  'case-manager': {
    profile: { role: 'admin', first_name: 'Dana' },
    title: 'Case manager',
    note: 'Sees their caseload and the §4.1 list — never message bodies.',
  },
  'super-admin': {
    profile: { role: 'super_admin', first_name: 'Will' },
    title: 'Super admin',
    note: 'Decides what happens to a flagged place, and sees the whole picture.',
  },
};

/** The journey, in the order a person meets it. */
const SCREENS = [
  { name: '1-sign-in', path: '/signin/' },
  // Sign-up, which for the stubbed profiles below lands on step 3 — the
  // screen that says what other people can see, and the one worth looking at.
  { name: '1b-sign-up', path: '/join/' },
  { name: '2-reminders', path: '/reminders/' },
  // Where everybody lands after the code works, and the screen that differs
  // most by role — a member is offered places, a case manager their caseload.
  { name: '3-home', path: '/' },
  { name: '4-places', path: '/places/' },
  // One place, on its own screen — where the way there, the hours and the
  // quieter actions live now that the card carries only what decides whether
  // to go.
  { name: '4b-place', path: '/place/?id=s1' },
  { name: '5-caseload', path: '/admin/' },
  // The super admin's own screen. Every other role meets a closed door here,
  // which is itself worth photographing — a closed door is a screen too.
  { name: '5b-everyone', path: '/directory/' },
  { name: '5c-saved', path: '/saved/' },
  { name: '5d-flag', path: '/flag/?place=s1' },
  { name: '5e-points', path: '/points/' },
  { name: '6-notifications', path: '/notifications/' },
  // One conversation — the screen with two pinned bars and a scrolling
  // middle (D-192). A member and their case manager see it from either side;
  // a super admin meets the "not for your role" notice, which is correct.
  // The conversation list — rows, the title that switches sections for a
  // case manager (D-197), and the one "New message" button.
  { name: '6a-messages', path: '/messages/' },
  { name: '6b-conversation', path: `/messages/thread/?id=${CONVO_ID}` },
  { name: '7-privacy', path: '/privacy/' },
  { name: '8-terms', path: '/terms/' },
  // Not a journey — the workbench. Photographed with the screens so a change to
  // a component shows up next to the screens it would have broken.
  { name: '9-components', path: '/gallery/' },
];

const DIRECTORY_PEOPLE = [
  {
    id: 'd1',
    first_name: 'Marcus',
    role: 'member',
    region_name: 'Philadelphia',
    access_status: 'active',
    last_active_at: new Date().toISOString(),
  },
  {
    id: 'd2',
    first_name: 'Alice',
    role: 'provider',
    region_name: 'Philadelphia',
    access_status: 'active',
    last_active_at: null,
  },
  {
    id: 'd3',
    first_name: 'Dana',
    role: 'admin',
    region_name: 'Philadelphia',
    access_status: 'limited',
    last_active_at: new Date(Date.now() - 86_400_000).toISOString(),
  },
];

const SAVED_PLACES = [
  {
    id: 's1',
    name: 'Example Learning Center',
    lookup_name: 'Example Learning Center',
    category: 'education',
    subcategory: null,
    address: '123 Main St',
    phone: '+12155550100',
    place_id: null,
    lat: 39.9526,
    lon: -75.1652,
    description_plain:
      'Free classes, a computer room and help getting a GED. Walk in and ask at the front desk.',
    website: 'https://example.org/learning',
    audience: null,
    hours: null,
  },
  {
    id: 's2',
    name: 'Example Workforce Center',
    lookup_name: 'Example Workforce Center',
    category: 'workforce',
    subcategory: null,
    address: '456 Market St',
    phone: null,
    place_id: null,
    lat: 39.9515,
    lon: -75.1605,
    description_plain:
      'Job training, help with a resume and openings posted every week. Free for people who live in the city.',
    website: null,
    audience: null,
    hours: null,
  },
  {
    id: 's3',
    name: 'Example Food Pantry',
    lookup_name: 'Example Food Pantry',
    category: 'family_services',
    subcategory: null,
    address: '789 Broad St',
    phone: '+12155550111',
    place_id: null,
    lat: 39.9612,
    lon: -75.1583,
    description_plain:
      'Groceries to take home, no appointment. Bring a bag if you have one.',
    website: null,
    audience: null,
    hours: null,
  },
];

const NOTIFICATIONS = [
  {
    id: 'n1',
    kind: 'service_flagged',
    body_key: 'notify.service_flagged',
    body_vars: { reason: 'closed', place: 'Example Learning Center' },
    subject_type: 'service',
    subject_id: 's1',
    created_at: new Date().toISOString(),
    read_at: null,
  },
  {
    id: 'n2',
    kind: 'message_reported',
    body_key: 'notify.message_reported',
    body_vars: { name: 'Marcus' },
    subject_type: 'report',
    subject_id: 'r1',
    created_at: new Date(Date.now() - 86_400_000).toISOString(),
    read_at: null,
  },
];

const CASELOAD = [
  { id: 'm1', first_name: 'Marcus', access_status: 'active', last_active_at: new Date().toISOString() },
  { id: 'm2', first_name: 'Tanya', access_status: 'active', last_active_at: null },
];

async function stub(page, profile) {
  if (profile) {
    await page.addInitScript((userId) => {
      const session = {
        access_token: 'preview',
        refresh_token: 'preview',
        token_type: 'bearer',
        expires_in: 3600,
        expires_at: Math.floor(Date.now() / 1000) + 3600,
        user: { id: userId, aud: 'authenticated', role: 'authenticated' },
      };
      for (const ref of ['stub', 'shobqzuhicoiymtumiaz']) {
        window.localStorage.setItem(`sb-${ref}-auth-token`, JSON.stringify(session));
      }
    }, ADMIN_ID);
    await page.route('**/auth/v1/user*', (r) => r.fulfill(json({ id: ADMIN_ID })));
  } else {
    await page.route('**/auth/v1/**', (r) => r.fulfill({ status: 401, body: '{}' }));
  }

  await page.route('**/rest/v1/profiles*', (r) =>
    r.request().url().includes('role=eq.member')
      ? r.fulfill(json(CASELOAD))
      : r.fulfill(
          json({
            id: ADMIN_ID,
            ...profile,
            region_id: '0195b1c0-0000-4000-8000-000000000001',
            regions: { name: 'Philadelphia' },
          }),
        ),
  );
  await page.route('**/rest/v1/notifications*', (r) => r.fulfill(json(NOTIFICATIONS)));
  await page.route('**/rest/v1/notification_preferences*', (r) => r.fulfill(json(null)));
  await page.route('**/rest/v1/access_controls*', (r) => r.fulfill(json([])));
  await page.route('**/rest/v1/rpc/member_points*', (r) => r.fulfill(json(400)));
  // The places list and one place's own screen draw the same rows, because
  // they are the same card and the same RPC shape.
  await page.route('**/rest/v1/rpc/services_near*', (r) =>
    r.fulfill(json(SAVED_PLACES.map((place, i) => ({ ...place, meters: 400 + i * 900 })))),
  );
  await page.route('**/rest/v1/rpc/service_detail*', (r) => r.fulfill(json([SAVED_PLACES[0]])));
  // The people directory. Stubbed rather than seeded, like every other query
  // here: this sheet is a picture of the screens, not of the database.
  await page.route('**/rest/v1/rpc/directory_people*', (r) =>
    r.fulfill(json(DIRECTORY_PEOPLE)),
  );
  await page.route('**/rest/v1/rpc/saved_places_mine*', (r) => r.fulfill(json(SAVED_PLACES)));
  await page.route('**/rest/v1/saved_places*', (r) => r.fulfill(json([])));
  await page.route('**/rest/v1/rpc/flag_service*', (r) => r.fulfill(json({ id: 'flag-1' })));
  await page.route('**/rest/v1/rpc/served_cities*', (r) =>
    r.fulfill(json([{ city: 'Philadelphia' }])),
  );
  // One conversation with Marcus, long enough to scroll (D-192).
  await page.route('**/rest/v1/conversation_members*', (r) => {
    if (r.request().method() === 'PATCH') return r.fulfill(json([]));
    if (r.request().url().includes('conversation_id=eq.')) {
      return r.fulfill(
        json([
          { profile_id: ADMIN_ID, conversations: { kind: 'direct' } },
          { profile_id: OTHER_ID, conversations: { kind: 'direct' } },
        ]),
      );
    }
    return r.fulfill(json([{ conversation_id: CONVO_ID, last_read_at: null }]));
  });
  await page.route('**/rest/v1/rpc/conversation_partners*', (r) =>
    r.fulfill(
      json([
        {
          conversation_id: CONVO_ID,
          profile_id: OTHER_ID,
          first_name: profile?.role === 'member' ? 'Teresa' : 'Marcus',
          role: profile?.role === 'member' ? 'admin' : 'member',
          program_name: null,
        },
      ]),
    ),
  );
  await page.route('**/rest/v1/messages*', (r) =>
    r.fulfill(
      json(
        [
          'Hi, it is Teresa. I put you down for the GED class. It starts Monday at 10.',
          'Thank you. Which bus goes there?',
          'The 47 stops right outside. It runs every 15 minutes in the morning.',
          'Got it. I will be there.',
          'How did Monday go?',
          'Good. The room was easy to find and the teacher is patient.',
          'Your ID appointment is Thursday at 2. Bring the letter I gave you.',
          'Thursday at 2. I have the letter.',
          'One more thing: the class moved to room 12 this week. Same time.',
        ].map((body, i) => ({
          id: `m-${i}`,
          conversation_id: CONVO_ID,
          sender_id: i % 2 === 0 ? (profile?.role === 'member' ? OTHER_ID : ADMIN_ID) : profile?.role === 'member' ? ADMIN_ID : OTHER_ID,
          body,
          created_at: new Date(Date.now() - (9 - i) * 3_600_000 * 6).toISOString(),
        })),
      ),
    ),
  );
  await page.route('**/rest/v1/rpc/messageable_people*', (r) => r.fulfill(json([])));
  await page.route('**/rest/v1/rpc/reports_for_review*', (r) => r.fulfill(json([])));
}

const server = spawn('npx', ['serve', 'apps/web/out', '-l', String(PORT), '--no-clipboard'], {
  cwd: new URL('..', import.meta.url).pathname,
  stdio: 'ignore',
});
await new Promise((resolve) => setTimeout(resolve, 2500));

rmSync(OUT, { recursive: true, force: true });
const browser = await chromium.launch({
  executablePath: process.env.PLAYWRIGHT_CHROMIUM_PATH || undefined,
});

const shots = [];
for (const [roleName, { profile }] of Object.entries(ROLES)) {
  mkdirSync(`${OUT}${roleName}`, { recursive: true });
  for (const theme of ['light', 'dark']) {
    for (const screen of SCREENS) {
      const page = await browser.newPage({
        viewport: { width: 390, height: 844 },
        // 1.5 rather than 2: readable on a laptop, and it keeps the whole sheet
        // small enough to ship inside the deployment.
        deviceScaleFactor: 1.5,
        colorScheme: theme,
      });
      await stub(page, profile);
      await page.goto(`${BASE}${screen.path}`, { waitUntil: 'networkidle' }).catch(() => {});
      await page.waitForTimeout(350);

      /*
       * Scroll the whole page, then come back.
       *
       * Cards reveal themselves as they are scrolled to, so a full-page shot of
       * a screen taller than the window captures everything below the fold at
       * opacity 0 — the points ladder came out with its bottom half blank. This
       * walks the page the way a person would, which settles every reveal, and
       * returns to the top so the shot starts where the screen does.
       */
      await page.evaluate(async () => {
        const step = window.innerHeight * 0.8;
        for (let y = 0; y < document.body.scrollHeight; y += step) {
          window.scrollTo(0, y);
          await new Promise((resolve) => setTimeout(resolve, 60));
        }
        window.scrollTo(0, 0);
        await new Promise((resolve) => setTimeout(resolve, 120));
      });
      const file = `${roleName}/${screen.name}-${theme}.png`;
      await page.screenshot({ path: `${OUT}${file}`, fullPage: true });
      shots.push({ role: roleName, screen: screen.name, theme, file, path: screen.path });
      await page.close();
    }
  }
  console.log(`photographed ${roleName}`);
}
await browser.close();
server.kill();

const roles = [...new Set(shots.map((s) => s.role))];
writeFileSync(
  `${OUT}index.html`,
  `<!doctype html><meta charset="utf-8"><title>PAM journeys</title>
<style>
 body{font:16px/1.5 system-ui;margin:0;padding:24px;background:#fafafa;color:#111}
 h1{font-size:22px} h2{font-size:18px;margin:32px 0 4px;text-transform:capitalize}
 p.note{color:#555;max-width:60ch}
 .row{display:flex;gap:12px;overflow-x:auto;padding:8px 0}
 figure{margin:0;flex:0 0 auto;width:200px}
 img{width:100%;border:1px solid #ddd;border-radius:8px;background:#fff}
 figcaption{font-size:12px;color:#555;padding-top:4px}
 .theme{font-size:12px;color:#888;margin-top:12px}
</style>
<h1>PAM — every screen, every role</h1>
<p class="note">Generated from the built app against stubbed data: real pages and
real styles, fake answers from the network. Nothing here talks to the live
database, so it stays truthful about the interface and says nothing about the
data.</p>
${roles
  .map(
    (role) => `<h2>${role.replace(/-/g, ' ')}</h2>` +
      ['light', 'dark']
        .map(
          (theme) =>
            `<div class="theme">${theme}</div><div class="row">` +
            shots
              .filter((s) => s.role === role && s.theme === theme)
              .map(
                (s) =>
                  `<figure><a href="${s.file}"><img src="${s.file}" alt="${role} ${s.screen}"></a>` +
                  `<figcaption>${s.screen.replace(/^\d-/, '')}<br>${s.path}</figcaption></figure>`,
              )
              .join('') +
            `</div>`,
        )
        .join(''),
  )
  .join('')}
`,
);

console.log(`\n${shots.length} screenshots -> docs/journeys/index.html`);
