import type { CapacitorConfig } from '@capacitor/cli';

/**
 * Capacitor wraps the Next.js static export (§1), so iOS, Android and the web
 * all run the same build. `webDir` points at the web app's `out/` — run
 * `pnpm --filter @pam/native sync` after any web change, or the shells ship
 * stale HTML.
 *
 * `ios/` and `android/` are generated by `cap add` and are not checked in; see
 * the root .gitignore.
 */
const config: CapacitorConfig = {
  appId: 'org.pam.app',
  appName: 'PAM',
  webDir: '../web/out',

  // §12: the app must work on a low-end Android 9 device with 2 GB of RAM.
  android: {
    // A member on a prepaid plan may be on a very old WebView. Keeping mixed
    // content off avoids silent asset failures on those devices.
    allowMixedContent: false,
  },

  ios: {
    contentInset: 'always',
  },

  plugins: {
    /**
     * §1 and §9: push is SECONDARY. SMS is the primary channel because many
     * members do not keep the app installed, and a text reaches a basic phone.
     * Push is registered here but nothing depends on it arriving.
     */
    PushNotifications: {
      presentationOptions: ['badge', 'sound', 'alert'],
    },
  },
};

export default config;
