/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/pam.theme.ts
 * Command: astryx theme build src/theme/pam.theme.ts
 * CLI: @astryxdesign/cli@0.6.0
 * Core: @astryxdesign/core@0.6.0
 */

/// <reference path="./pam.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const pamTheme: DefinedTheme;
