/**
 * Writes `src/styles/tokens.css` — every design token Pam uses, as plain CSS
 * custom properties, in one file (Will, 6 October: "Centralize tokens. Keep
 * colors, spacing, radii, and type in one CSS variables file that the
 * component stylesheet imports").
 *
 * The file is generated, never edited by hand, from the three places the
 * values really live:
 *
 *   1. Astryx's defaults — spacing, radii, shadows, motion, the type scale
 *      (`@astryxdesign/core/astryx.css`, its `:root` blocks).
 *   2. Pam's theme, which overrides colour and type
 *      (`src/theme/pam.css`, built from `pam.theme.ts` by `pnpm theme`).
 *   3. Pam's own measurements — touch target, field height, page width
 *      (`src/tokens.stylex.ts`, the `--pam-*` keys).
 *
 * Later sources win, as they do in the browser. Run after changing any of
 * them:  pnpm --filter @pam/ui tokens   (`--check` fails on drift; the unit
 * tests run it).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkg = join(here, '..');
const require = createRequire(import.meta.url);
const OUT = join(pkg, 'src/styles/tokens.css');

const FAMILIES = /^--(color|spacing|size|radius|font|text|shadow|duration|ease|line-height|elevation|z)-/;

/** Declarations inside every block whose selector is `:root` or `:scope`. */
function rootDeclarations(css) {
  const found = new Map();
  const opener = /(^|[\s{};])(:root|:scope)(\s*,[^{}]*)?\s*\{/g;
  let m;
  while ((m = opener.exec(css))) {
    let i = opener.lastIndex;
    let depth = 1;
    const start = i;
    while (i < css.length && depth > 0) {
      if (css[i] === '{') depth += 1;
      else if (css[i] === '}') depth -= 1;
      i += 1;
    }
    const body = css.slice(start, i - 1).replace(/\/\*[\s\S]*?\*\//g, '');
    for (const decl of body.matchAll(/(--[a-z0-9-]+)\s*:\s*([^;{}]+);/gi)) {
      const [, name, value] = decl;
      if (FAMILIES.test(name) && !found.has(name)) found.set(name, value.trim());
    }
  }
  return found;
}

function pamMeasurements(ts) {
  const found = new Map();
  for (const m of ts.matchAll(/'(--pam-[a-z0-9-]+)'\s*:\s*'([^']+)'/g)) found.set(m[1], m[2]);
  return found;
}

const astryx = rootDeclarations(readFileSync(require.resolve('@astryxdesign/core/astryx.css'), 'utf8'));
const theme = rootDeclarations(readFileSync(join(pkg, 'src/theme/pam.css'), 'utf8'));
const pam = pamMeasurements(readFileSync(join(pkg, 'src/tokens.stylex.ts'), 'utf8'));

const merged = new Map(astryx);
for (const [k, v] of theme) merged.set(k, v);

const GROUPS = [
  ['Colour', (n) => n.startsWith('--color-') && !n.startsWith('--color-data-') && !n.startsWith('--color-syntax-')],
  ['Colour — data (charts, category art)', (n) => n.startsWith('--color-data-')],
  ['Colour — code', (n) => n.startsWith('--color-syntax-')],
  ['Spacing', (n) => n.startsWith('--spacing-')],
  ['Sizes — controls', (n) => n.startsWith('--size-')],
  ['Radius', (n) => n.startsWith('--radius-')],
  ['Type — families, sizes, weights', (n) => n.startsWith('--font-') || n.startsWith('--line-height-')],
  ['Type — roles (heading, body, label…)', (n) => n.startsWith('--text-')],
  ['Elevation', (n) => n.startsWith('--shadow-') || n.startsWith('--elevation-')],
  ['Motion', (n) => n.startsWith('--duration-') || n.startsWith('--ease-')],
  ['Layering', (n) => n.startsWith('--z-')],
];

const lines = [];
lines.push('/*');
lines.push(' * @generated by packages/ui/scripts/tokens.mjs — do not edit by hand.');
lines.push(' *');
lines.push(' * Every design token Pam uses, as CSS custom properties. Sources, later');
lines.push(' * winning: Astryx defaults (astryx.css), Pam\'s theme (theme/pam.css, from');
lines.push(' * pam.theme.ts), Pam\'s measurements (tokens.stylex.ts). Change those, then');
lines.push(' * run `pnpm --filter @pam/ui tokens`.');
lines.push(' *');
lines.push(' * Colours are `light-dark()` pairs: they follow `color-scheme`, set below.');
lines.push(' */');
lines.push('');
lines.push(':root {');
lines.push('  color-scheme: light dark;');
const used = new Set();
for (const [title, test] of GROUPS) {
  const names = [...merged.keys()].filter((n) => !used.has(n) && test(n));
  if (names.length === 0) continue;
  lines.push('');
  lines.push(`  /* ${title} */`);
  for (const n of names) {
    used.add(n);
    lines.push(`  ${n}: ${merged.get(n)};`);
  }
}
const rest = [...merged.keys()].filter((n) => !used.has(n));
if (rest.length) {
  lines.push('');
  lines.push('  /* Other */');
  for (const n of rest) lines.push(`  ${n}: ${merged.get(n)};`);
}
lines.push('');
lines.push('  /* Pam — the accessibility floor and page measurements (SOP §0, §2.5) */');
for (const [n, v] of pam) lines.push(`  ${n}: ${v};`);
lines.push('}');
lines.push('');
const out = lines.join('\n');

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(OUT, 'utf8');
  } catch {
    // missing counts as drift
  }
  if (current !== out) {
    console.error('src/styles/tokens.css is out of date — run `pnpm --filter @pam/ui tokens`.');
    process.exit(1);
  }
  console.log('tokens.css is current');
} else {
  writeFileSync(OUT, out);
  console.log(`wrote ${OUT} — ${merged.size + pam.size} tokens`);
}
